name: Docker

on:
  push:
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Descargar código
        uses: actions/checkout@v4
      - name: Comprobar secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USER }}" ]; then
            echo "ERROR: DOCKERHUB_USER está vacío"
            exit 1
          fi

          if [ -z "${{ secrets.DOCKERHUB_PASS }}" ]; then
            echo "ERROR: DOCKERHUB_PASS está vacío"
            exit 1
          fi

          echo DOCKER_USERNAME
          echo DOCKER_PASSWORD
      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Construir imagen
        run: docker build -t ${{ secrets.DOCKERHUB_USER }}/imglibros .

      - name: Analizar vulnerabilidades
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ secrets.DOCKERHUB_USER }}/imglibros

      - name: Publicar imagen
        run: docker push ${{ secrets.DOCKERHUB_USER  }}/imglibros